name: Build and push Docker Hub

on:
  push:
    branches: [ "main", "master"]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com
  IMAGE: aikedejongste/db-dumper

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.2.0
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest
